flux:
	(cd Flux/Source; ../../Scripts/clr; make clean; make)
neoclassical:
	(cd Neoclassical/Source; ../../Scripts/clr; make clean; make)
phase:
	(cd Phase/Source; ../../Scripts/clr; make clean; make)
rescale:
	(cd Rescale/Source; ../../Scripts/clr; make clean; make)
html:
	(cd Sphinx; make html)
all:
	(cd Flux/Source; ../../Scripts/clr; make clean; make)
	(cd Neoclassical/Source; ../../Scripts/clr; make clean; make)
	(cd Phase/Source; ../../Scripts/clr; make clean; make)
	(cd Rescale/Source; ../../Scripts/clr; make clean; make)
	(cd Sphinx; make html)

test1:
	(cp TestData/DIIID145380.3400/Flux.nml Flux/Inputs/Flux.nml)
	(cp TestData/DIIID145380.3400/gFile Flux/Inputs/gFile)
	(cp TestData/DIIID145380.3400/Neoclassical.nml Neoclassical/Inputs/Neoclassical.nml)
	(cp TestData/DIIID145380.3400/pFile Neoclassical/Inputs/pFile)
	(cp TestData/DIIID145380.3400/cFile Neoclassical/Inputs/cFile)
	(cp TestData/DIIID145380.3400/Phase.nml Phase/Inputs/Phase.nml)
	(cp TestData/DIIID145380.3400/Waveform.nml Phase/Inputs/Waveform.nml)
	(cp TestData/DIIID145380.3400/lFile Phase/Inputs/lFile)
	(cp TestData/DIIID145380.3400/uFile Phase/Inputs/uFile)
	(cd Flux; ./flux)
	(cp Flux/Outputs/fFile Neoclassical/Inputs/fFile)
	(cp Flux/Outputs/fFile Phase/Inputs/fFile)	
	(cd Neoclassical; ./neoclassical)
	(cp Neoclassical/Outputs/nFile Phase/Inputs/nFile)	
	(cd Phase; ./phase)
	(cd TestData/DIIID145380.3400; ./ChecksumTest)
test2:
	(cp TestData/KSTAR18594.6450/Flux.nml Flux/Inputs/Flux.nml)
	(cp TestData/KSTAR18594.6450/gFile Flux/Inputs/gFile)
	(cp TestData/KSTAR18594.6450/Neoclassical.nml Neoclassical/Inputs/Neoclassical.nml)
	(cp TestData/KSTAR18594.6450/pFile Neoclassical/Inputs/pFile)
	(cp TestData/KSTAR18594.6450/cFile Neoclassical/Inputs/cFile)
	(cp TestData/KSTAR18594.6450/Phase.nml Phase/Inputs/Phase.nml)
	(cp TestData/KSTAR18594.6450/Waveform.nml Phase/Inputs/Waveform.nml)
	(cp TestData/KSTAR18594.6450/lFile Phase/Inputs/lFile)
	(cp TestData/KSTAR18594.6450/mFile Phase/Inputs/mFile)
	(cp TestData/KSTAR18594.6450/uFile Phase/Inputs/uFile)
	(cd Flux; ./flux)
	(cp Flux/Outputs/fFile Neoclassical/Inputs/fFile)
	(cp Flux/Outputs/fFile Phase/Inputs/fFile)	
	(cd Neoclassical; ./neoclassical)
	(cp Neoclassical/Outputs/nFile Phase/Inputs/nFile)	
	(cd Phase; ./phase)
	(cd TestData/KSTAR18594.6450; ./ChecksumTest)
test3:
	(cp TestData/NSTX127317.00400/Flux.nml Flux/Inputs/Flux.nml)
	(cp TestData/NSTX127317.00400/gFile Flux/Inputs/gFile)
	(cp TestData/NSTX127317.00400/Neoclassical.nml Neoclassical/Inputs/Neoclassical.nml)
	(cp TestData/NSTX127317.00400/pFile Neoclassical/Inputs/pFile)
	(cp TestData/NSTX127317.00400/cFile Neoclassical/Inputs/cFile)
	(cp TestData/NSTX127317.00400/Phase.nml Phase/Inputs/Phase.nml)
	(cp TestData/NSTX127317.00400/Waveform.nml Phase/Inputs/Waveform.nml)
	(cp TestData/NSTX127317.00400/lFile Phase/Inputs/lFile)
	(cd Flux; ./flux)
	(cp Flux/Outputs/fFile Neoclassical/Inputs/fFile)
	(cp Flux/Outputs/fFile Phase/Inputs/fFile)	
	(cd Neoclassical; ./neoclassical)
	(cp Neoclassical/Outputs/nFile Phase/Inputs/nFile)	
	(cd Phase; ./phase)
	(cd TestData/NSTX127317.00400; ./ChecksumTest)
