#!/bin/bash

if test -f "../../Phase/Outputs/Stage5.nc"; then
:
else
   echo "Error: Stage5.nc not found"; exit 1
fi	
CHECKSUM1=( $(shasum -a 256 ../../Phase/Outputs/Stage5.nc) )
CHECKSUM2=( $(shasum -a 256 Stage5.nc) )

if [ ${CHECKSUM1[0]} != ${CHECKSUM2[0]} ]; then
   echo "Checksum error"; exit 1
fi
echo "#############"
echo "Test 2 passed"
echo "#############"
exit 0
