#!/bin/csh

# Clean-up script

rm -f *.aux >& /dev/null
rm -f *.dvi >& /dev/null
rm -f *.log >& /dev/null
rm -f *.tmp >& /dev/null
rm -f *~    >& /dev/null
rm -f .*~   >& /dev/null
rm -f *.bak >& /dev/null
