#!/bin/bash

# Script to copy output from Stages 1 to 3 (i.e., FLUX and NEOCLASSICAL)
# to pwd

CWD="$(pwd)"
cd /Users/rfitzp/GitHub/EPEC-source
tar  --dereference --exclude='*.eps' -c -v -z -f tarfile.tgz Flux/Inputs/* Flux/Outputs/* Flux/Plots/* Neoclassical/Inputs/* Neoclassical/Outputs/* Neoclassical/Plots/* 
cd $CWD
mv /Users/rfitzp/GitHub/EPEC-source/tarfile.tgz .
tar xvfz tarfile.tgz
rm tarfile.tgz

