#!/bin/bash

# Script to copy output from Stages 1 to 5 (i.e., FLUX, NEOCLASSICAL, PHASE)
# to pwd

CWD="$(pwd)"
cd /Users/rfitzp/EPEC
tar --dereference --exclude='*.eps' -c -v -z -f tarfile.tgz Flux/Inputs/* Flux/Outputs/* Flux/Plots/* Neoclassical/Inputs/* Neoclassical/Outputs/* Neoclassical/Plots/* Phase/Inputs/* Phase/Outputs/* Phase/Plots/* 
cd $CWD
mv /Users/rfitzp/EPEC/tarfile.tgz .
tar xvfz tarfile.tgz
rm tarfile.tgz

