#!/bin/bash

# Script to copy output from Stages 1 to 6 (i.e., FLUX, NEOCLASSICAL, PHASE, ISLANDDYNAMICS)
# to pwd

CWD="$(pwd)"
cd /Users/rfitzp/GitHub/EPEC-source
tar --dereference --exclude='*.eps' -c -v -z -f tarfile.tgz Flux/Inputs/* Flux/Outputs/* Flux/Plots/* Neoclassical/Inputs/* Neoclassical/Outputs/* Neoclassical/Plots/* Phase/Inputs/* Phase/Outputs/* Phase/Plots/* IslandDynamics/Inputs/* IslandDynamics/Outputs/* IslandDynamics/Plots/*  
cd $CWD
mv /Users/rfitzp/GitHub/EPEC-source/tarfile.tgz .
tar xvfz tarfile.tgz
rm tarfile.tgz

