#!/bin/bash

set -e

machine=$(uname -n)

if [[ "$machine" == *"iris"* ]]
then
  host="iris"
elif [[ "$machine" == *"CNS"* ]]
then
    host="utexas"
elif [[ "$machine" == *"Richard"* ]]
then
  host="utexas" 
fi

if [[ "$host" == "iris" ]]
then
    module purge
    module load netcdf
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/cscratch/fitzpatrickr/lib
    export LD_LIBRARY_PATH
elif  [[ "$host" == "utexas" ]]
then
    :
fi

# ################
# Run Neoclassical
# ################

if [ ! -d "Neoclassical" ]
then
    mkdir Neoclassical
fi
if [ ! -d "Neoclassical/Outputs" ]        
then
    mkdir Neoclassical/Outputs
fi
if [ ! -d "Neoclassical/Outputs/Stage3" ] 
then
    mkdir Neoclassical/Outputs/Stage3
fi

cd Neoclassical
neoclassical

