#!/bin/bash

machine=$(uname -n)

if [[ "$machine" == *"iris"* ]]
then
  host="iris"
elif [[ "$machine" == *"CNS"* ]]
then
    host="utexas"
elif [[ "$machine" == *"Richard"* ]]
then
  host="utexas" 
fi

if [[ "$host" == "iris" ]]
then
    module purge
    module load netcdf
    LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/cscratch/fitzpatrickr/lib
    export LD_LIBRARY_PATH
elif  [[ "$host" == "utexas" ]]
then
    :
fi

if [ ! -d "Outputs" ]        
then
    mkdir Outputs
fi
if [ ! -d "Outputs/Stage1" ] 
then
    mkdir Outputs/Stage1
fi
if [ ! -d "Outputs/Stage2" ] 
then
    mkdir Outputs/Stage2
fi

flux
